const sampleListing_p = [
    {
        name: "Rahul Sharma",
        adhar: 123456789012,
        dob: "1990-05-12",
        age: 34,
        gender: "Male",
        phone: 9876543210,
        email: "rahul.sharma@example.com",
        address: "123 Street, Pune, India",
        emName: "Rakesh Sharma",
        emRel: "Father",
        emCall: 9123456789,
        isMarried: false,
        bloodGr: "B+",
        occup: "Software Engineer",
        nation: "Indian",
        lang: "Hindi",
        famMedHis: "None",
        allergy: "Pollen",
        allergyNote: "Mild allergy to pollen.",
        longDisease: "None",
        surgeryTyp: "None",
        surgeryDate: "",
        surgeon: "",
        surgeryNote: "",
        reasonApp: "General Checkup",
        durationApp: "30 mins",
        dateApp: "2024-09-15",
        doctorApp: "Dr. Mehta",
        noteApp: "Patient is healthy.",
        vaccineTyp: "COVID-19",
        vaccineDate: "2023-01-05",
        vaccineDoses: "2",
        vaccineCenter: "Apollo Hospital",
        medicineUsing: "None",
        medicineDose: "",
        medicineDays: "",
        medicineNote: "",
        nowServerity: 0,
        exercise: "Regular",
        sleep: "8 hours",
        diet: "Balanced",
        pastMedUsing: "None",
        pastMedReason: "",
        pastMedDose: "",
        pastMedDays: "",
        pastMedNote: "",
        pastServerity: "",
        pastExercise: "None",
        pastSleep: "7 hours",
        pastDiet: "Normal",
        labResultImg1: "",
        labResultImg2: "",
        bmi: 23.5,
        bp: 120,
        heartRate: 72,
        weight: 70,
        height: 175,
        insuranceName: "HealthGuard Premium",
        insuranceSource: "XYZ Insurance Co.",
        insuranceId: "INS12345678",
        note: "No issues found.",
        img: {
            filename: "patientimg",
            url: "https://plus.unsplash.com/premium_photo-1682437977998-0a1162c3219f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjV8fGZvcm1hbCUyMG1hbnxlbnwwfHwwfHx8MA%3D%3D"
        }
    },
    {
        name: "Priya Verma",
        adhar: 987654321098,
        dob: "1992-07-22",
        age: 32,
        gender: "Female",
        phone: 9876543222,
        email: "priya.verma@example.com",
        address: "456 Avenue, Mumbai, India",
        emName: "Anita Verma",
        emRel: "Mother",
        emCall: 9234567890,
        isMarried: true,
        bloodGr: "O+",
        occup: "Teacher",
        nation: "Indian",
        lang: "English, Marathi",
        famMedHis: "Diabetes",
        allergy: "None",
        allergyNote: "",
        longDisease: "None",
        surgeryTyp: "Appendectomy",
        surgeryDate: "2018-05-10",
        surgeon: "Dr. Nair",
        surgeryNote: "Successful surgery.",
        reasonApp: "Flu symptoms",
        durationApp: "45 mins",
        dateApp: "2024-08-22",
        doctorApp: "Dr. Kulkarni",
        noteApp: "Prescribed antibiotics.",
        vaccineTyp: "Influenza",
        vaccineDate: "2024-01-15",
        vaccineDoses: "1",
        vaccineCenter: "Fortis Hospital",
        medicineUsing: "Azithromycin",
        medicineDose: "500 mg",
        medicineDays: "5 days",
        medicineNote: "Take after food.",
        nowServerity: 2,
        exercise: "Occasional",
        sleep: "7 hours",
        diet: "Vegetarian",
        pastMedUsing: "None",
        pastMedReason: "",
        pastMedDose: "",
        pastMedDays: "",
        pastMedNote: "",
        pastServerity: "",
        pastExercise: "Regular",
        pastSleep: "6 hours",
        pastDiet: "Low carb",
        labResultImg1: "",
        labResultImg2: "",
        bmi: 22.1,
        bp: 115,
        heartRate: 75,
        weight: 60,
        height: 165,
        insuranceName: "LifeSecure Plan",
        insuranceSource: "ABC Life Insurance",
        insuranceId: "INS98765432",
        note: "Mild flu symptoms.",
        img: {
            filename: "patientimg",
            url: "https://plus.unsplash.com/premium_photo-1664477129473-35c28d5446f2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8b2ZmaWNlJTIwd29tYW58ZW58MHx8MHx8fDA%3D"
        }
    },
    {
        name: "Amit Desai",
        adhar: 456789123456,
        dob: "1985-02-25",
        age: 39,
        gender: "Male",
        phone: 8887654321,
        email: "amit.desai@example.com",
        address: "789 Lane, Delhi, India",
        emName: "Sunita Desai",
        emRel: "Wife",
        emCall: 9345678901,
        isMarried: true,
        bloodGr: "AB+",
        occup: "Lawyer",
        nation: "Indian",
        lang: "English, Gujarati",
        famMedHis: "Heart Disease",
        allergy: "Peanuts",
        allergyNote: "Severe peanut allergy.",
        longDisease: "Hypertension",
        surgeryTyp: "None",
        surgeryDate: "",
        surgeon: "",
        surgeryNote: "",
        reasonApp: "Blood pressure check",
        durationApp: "20 mins",
        dateApp: "2024-09-01",
        doctorApp: "Dr. Singh",
        noteApp: "Blood pressure is stable.",
        vaccineTyp: "Tetanus",
        vaccineDate: "2023-11-20",
        vaccineDoses: "1",
        vaccineCenter: "Max Hospital",
        medicineUsing: "Losartan",
        medicineDose: "50 mg",
        medicineDays: "Ongoing",
        medicineNote: "Monitor blood pressure.",
        nowServerity: 3,
        exercise: "Walking",
        sleep: "6 hours",
        diet: "Low sodium",
        pastMedUsing: "None",
        pastMedReason: "",
        pastMedDose: "",
        pastMedDays: "",
        pastMedNote: "",
        pastServerity: "",
        pastExercise: "None",
        pastSleep: "7 hours",
        pastDiet: "Normal",
        labResultImg1: "",
        labResultImg2: "",
        bmi: 24.8,
        bp: 130,
        heartRate: 78,
        weight: 80,
        height: 170,
        insuranceName: "AutoProtect Comprehensive",
        insuranceSource: "AutoSafe Insurance",
        insuranceId: "INS45678901",
        note: "Hypertension managed well.",
        img: {
            filename: "patientimg",
            url: "https://images.unsplash.com/photo-1622020920816-cd528763211a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzF8fGZvcm1hbCUyMG1hbnxlbnwwfHwwfHx8MA%3D%3D"
        }
    },
    {
        name: "Sneha Kapoor",
        adhar: 789012345678,
        dob: "1995-11-10",
        age: 28,
        gender: "Female",
        phone: 9876543299,
        email: "sneha.kapoor@example.com",
        address: "101 Block, Kolkata, India",
        emName: "Raj Kapoor",
        emRel: "Father",
        emCall: 9123456790,
        isMarried: false,
        bloodGr: "A-",
        occup: "Artist",
        nation: "Indian",
        lang: "Bengali, English",
        famMedHis: "Asthma",
        allergy: "Dust",
        allergyNote: "Mild dust allergy.",
        longDisease: "None",
        surgeryTyp: "None",
        surgeryDate: "",
        surgeon: "",
        surgeryNote: "",
        reasonApp: "Asthma checkup",
        durationApp: "30 mins",
        dateApp: "2024-10-05",
        doctorApp: "Dr. Bose",
        noteApp: "Asthma is under control.",
        vaccineTyp: "Hepatitis B",
        vaccineDate: "2022-09-15",
        vaccineDoses: "3",
        vaccineCenter: "Ruby General Hospital",
        medicineUsing: "Salbutamol",
        medicineDose: "100 mcg",
        medicineDays: "As needed",
        medicineNote: "Take during asthma episodes.",
        nowServerity: 1,
        exercise: "Occasional",
        sleep: "8 hours",
        diet: "Healthy",
        pastMedUsing: "None",
        pastMedReason: "",
        pastMedDose: "",
        pastMedDays: "",
        pastMedNote: "",
        pastServerity: "",
        pastExercise: "None",
        pastSleep: "7 hours",
        pastDiet: "Normal",
        labResultImg1: "",
        labResultImg2: "",
        bmi: 21.2,
        bp: 110,
        heartRate: 70,
        weight: 55,
        height: 160,
        insuranceName: "FamilyHealth Plan",
        insuranceSource: "HealthFirst Insurance",
        insuranceId: "INS98765499",
        note: "Asthma is managed well.",
        img: {
            filename: "patientimg",
            url: "https://plus.unsplash.com/premium_photo-1661538928730-ea06a623a885?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8b2ZmaWNlJTIwd29tYW58ZW58MHx8MHx8fDA%3D"
        }
    },
    {
        name: "Ravi Patel",
        adhar: 112233445566,
        dob: "1988-03-17",
        age: 36,
        gender: "Male",
        phone: 9876543211,
        email: "ravi.patel@example.com",
        address: "23 Lane, Ahmedabad, India",
        emName: "Kiran Patel",
        emRel: "Brother",
        emCall: 9234567812,
        isMarried: true,
        bloodGr: "A+",
        occup: "Civil Engineer",
        nation: "Indian",
        lang: "Gujarati, Hindi",
        famMedHis: "Hypertension",
        allergy: "None",
        allergyNote: "",
        longDisease: "None",
        surgeryTyp: "None",
        surgeryDate: "",
        surgeon: "",
        surgeryNote: "",
        reasonApp: "Routine Checkup",
        durationApp: "15 mins",
        dateApp: "2024-09-10",
        doctorApp: "Dr. Desai",
        noteApp: "Healthy, no issues.",
        vaccineTyp: "COVID-19",
        vaccineDate: "2022-03-12",
        vaccineDoses: "2",
        vaccineCenter: "Civil Hospital",
        medicineUsing: "None",
        medicineDose: "",
        medicineDays: "",
        medicineNote: "",
        nowServerity: 0,
        exercise: "Daily",
        sleep: "7 hours",
        diet: "Balanced",
        pastMedUsing: "None",
        pastMedReason: "",
        pastMedDose: "",
        pastMedDays: "",
        pastMedNote: "",
        pastServerity: "",
        pastExercise: "None",
        pastSleep: "6 hours",
        pastDiet: "Regular",
        labResultImg1: "",
        labResultImg2: "",
        bmi: 24.0,
        bp: 118,
        heartRate: 70,
        weight: 75,
        height: 172,
        insuranceName: "SecureLife Policy",
        insuranceSource: "Patel Insurance Co.",
        insuranceId: "INS22334455",
        note: "Overall in good health.",
        img: {
            filename: "patientimg",
            url: "https://media.istockphoto.com/id/944300692/photo/cheerful-young-athlete-outdoors-by-the-river.webp?a=1&b=1&s=612x612&w=0&k=20&c=i0CgTiuY_c96tV5TPdQ1UKOLntK3P1TsnDFI_s3TUMo="
        }
    },
];



module.exports = { data_p : sampleListing_p };// This data_p name is going to be used in index_p.js in insertMany function after '.'.